print("Range examples")
a=range(1,11)
l1=list(a)
print("Normal range:",l1)
b=range(1,11,2)
l2=list(b)
print("Range with step 2:",l2)
c=range(1,-11,-1)
l3=list(c)
print("Range with negative step and final value:",l3)
d=range(1,0)
l4=list(d)
print("Range (1,0) is ",l4)