a=(10,20,30,40,50)
print("Tuple example")
print(a)
print(type(a))
b=(60,70)
print("Concatenation with (60,70)")
print(a+b)
print("Repetition twice")
print(a*2)
print("Slicing")
print(a[1:3])
print("Indexing")
print(a[3])
